name: banco_finandina
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.1
  google_fonts: ^3.0.1
  introduction_screen: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/introduction_items/
    - assets/images/introduction_backgrounds/
